timezone: UTC
author:
  full_name: &title INA Lintaro
  description: &description A software engineer.
  image: &image https://avatars2.githubusercontent.com/u/132569?s=460&v=4
  sns:
    hatena: tarao
    twitter: oarat
    github: tarao
  blog:
    title: 貳佰伍拾陸夜日記
    url: https://tarao.hatenablog.com/
    icon: /img/hatenablog.svg
title: *title
favicon:
  url: *image
  type: image/png
og:
  title: *title
  description: *description
  image: *image
google_analytics:
  id: UA-156069885-1
clarity:
  id: 5ycdnncbnu
exclude:
  - README.md
  - LICENSE
  - Makefile
