name: Deployment
on:
  push:
    branches:
      - source
  schedule:
    - cron: '0 20 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Jekyll
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GitHubToken }}
        env:
          GITHUB_TOKEN: ${{ secrets.GitHubToken }}
